on: [push]
jobs:
  test:
    name: Test config on ${{matrix.node}}
    runs-on: docker
    strategy:
      matrix:
        node: ["20"]

    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup NodeJS
        uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}

      - name: Install eask
        run: npm install -g @emacs-eask/cli

      - name: Run tests
        run: eask test buttercup

      - name: Uninstall eask
        run: npm uninstall -g @emacs-eask/cli
